apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ai.dotglitch.dev-ingress
spec:
  entryPoints:
   - web
  routes:
    - match: Host(`dev.ai.dotglitch.dev`)
      kind: Rule
      services:
      - name: ai-art
        port: 80

---

apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ai.dotglitch.dev-secure-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`dev.ai.dotglitch.dev`)
      services:
        - name: ai-art
          port: 80
  tls:
    secretName: dev.ai.dotglitch.dev-tls

---

apiVersion: v1
kind: Service
metadata:
  name: ai-art
spec:
  selector:
    app: ai-art
  ports:
  - protocol: "TCP"
    port: 80
    targetPort: 80
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-art
spec:
  selector:
    matchLabels:
      app: ai-art
  replicas: 1
  template:
    metadata:
      labels:
        app: ai-art
    spec:
      containers:
      - name: ai-art
        image: harbor.dotglitch.dev/library/ai-art:latest
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: harbor-key

---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev.ai.dotglitch.dev
spec:
  commonName: dev.ai.dotglitch.dev
  dnsNames:
    - dev.ai.dotglitch.dev
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-stage
  secretName: dev.ai.dotglitch.dev-tls


